# Generated by Django 3.2.7 on 2021-10-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateStart', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('DateStop', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('employee_close', models.CharField(blank=True, max_length=20, null=True, verbose_name='Сотрудник закрывший заявку')),
                ('Ship', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название лодки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Метаданные')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время отправки')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.appl', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Telegram')),
                ('telegram_username', models.CharField(max_length=20, verbose_name='Сотрудник закрывший заявку')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.appl', verbose_name='Заявки клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
