# Generated by Django 3.2.7 on 2021-10-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appl',
            name='Active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
