# Generated by Django 3.2.7 on 2021-10-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_appl_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chat_id',
            field=models.CharField(default=0, max_length=20, verbose_name='id чата'),
            preserve_default=False,
        ),
    ]
